### ISSUE TITLE
Discount percent could be a configurable parameter

### ISSUE THREAD

**Issue by mirzafasi** [mudassirshahzad/retail-service#1]
https://github.com/mudassirshahzad/retail-service/blob/36dc7937cd7e6f4e4750f44a80f1e5a0b4c77793/src/main/java/com/mudassirshahzad/retailservice/services/RetailServiceImpl.java#L58

**Comment by mirzafasi** [comment]
Discount changes frequently, it could be externalized

**Comment by mudassirshahzad** [comment]
Completely agree. It's just a prototype. You're welcome to change it :)

**Comment by mudassirshahzad** [comment]
Resolved in the commit 1a8e8f5bb5a66010e7689b6181f06051edda5ea6
